### ISSUE TITLE
java.lang.Exception: ReKotlin:ConcurrentMutationError- Action has been dispatched while a previous action is action is being processed. A reducer is dispatching an action, or ReKotlin is used in a concurrent context (e.g. from multiple threads).

### ISSUE THREAD

**Issue by alpesh-einfochips** [ReKotlin/ReKotlin#49]
org.rekotlin.Store._defaultDispatch Store.kt:125
org.rekotlin.Store$dispatchFunction$1.invoke Store.kt:53
org.rekotlin.Store$dispatchFunction$1.invoke Store.kt:29
com.outsidesource.oskit.domain.store.middleware.effectReducer.MiddlewareKt$createEffectReducerMiddleware$1$1$1.invoke Middleware.kt:48
com.outsidesource.oskit.domain.store.middleware.effectReducer.MiddlewareKt$createEffectReducerMiddleware$1$1$1.invoke
com.outsidesource.oskit.domain.store.middleware.ActionCoordinator$createMiddleware$1$1$1.invoke ActionCoordinator.kt:79
com.outsidesource.oskit.domain.store.middleware.ActionCoordinator$createMiddleware$1$1$1.invoke ActionCoordinator.kt:59
org.rekotlin.Store.dispatch Store.kt:141
org.rekotlin.Store$$special$$inlined$fold$lambda$1.invoke Store.kt:54
org.rekotlin.Store$$special$$inlined$fold$lambda$1.invoke Store.kt:29
com.outsidesource.oskit.domain.store.middleware.effectReducer.MiddlewareKt$handleDispatchEffect$2.invokeSuspend Middleware.kt:239
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith ContinuationImpl.kt:33
kotlinx.coroutines.DispatchedTask.run DispatchedTask.kt:106
android.os.Handler.handleCallback Handler.java:942
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loopOnce Looper.java:226
android.os.Looper.loop Looper.java:313
android.app.ActivityThread.main ActivityThread.java:8762
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:604
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1067

**Comment by albertB4work** [comment]
Is this being reviewed? I have a lot of users with this exception crashing (but i don't arrive to reproduce it). This is the problem when you use external libraries in your apps, when the support ends there is a big problem with a big architecture to change

**Comment by albertB4work** [comment]
```
Caused by java.lang.Exception: ReKotlin:ConcurrentMutationError- Action has been dispatched while a previous action is action is being processed. A reducer is dispatching an action, or ReKotlin is used in a concurrent context (e.g. from multiple threads).
       at org.rekotlin.Store._defaultDispatch(Store.kt:125)
       at org.rekotlin.Store$dispatchFunction$1.invoke(Store.kt:53)
       at org.rekotlin.Store$dispatchFunction$1.invoke(Store.kt:29)
       at com.innopro.b4work.data.middleware.NpsMiddleware$middleware$1$1$1.invoke(NpsMiddleware.kt:46)
       at com.innopro.b4work.data.middleware.NpsMiddleware$middleware$1$1$1.invoke(NpsMiddleware.kt:24)
       at com.innopro.b4work.data.middleware.AlertsMiddleware$middleware$1$1$1.invoke(AlertsMiddleware.kt:33)
       at com.innopro.b4work.data.middleware.AlertsMiddleware$middleware$1$1$1.invoke(AlertsMiddleware.kt:24)
       at com.innopro.b4work.data.middleware.CompanyStatusMiddleware$middleware$1$1$1.invoke(CompanyStatusMiddleware.kt:23)
       at com.innopro.b4work.data.middleware.CompanyStatusMiddleware$middleware$1$1$1.invoke(CompanyStatusMiddleware.kt:14)
       at com.innopro.b4work.data.middleware.ChatMiddleware$middleware$1$1$1.invoke(ChatMiddleware.kt:23)
       at com.innopro.b4work.data.middleware.ChatMiddleware$middleware$1$1$1.invoke(ChatMiddleware.kt:17)
       at com.innopro.b4work.data.middleware.NotificationMiddleware$middleware$1$1$1.invoke(NotificationMiddleware.kt:20)
       at com.innopro.b4work.data.middleware.NotificationMiddleware$middleware$1$1$1.invoke(NotificationMiddleware.kt:15)
       at com.innopro.b4work.data.middleware.SelectorMiddleware$middleware$1$1$1.invoke(SelectorMiddleware.kt:22)
       at com.innopro.b4work.data.middleware.SelectorMiddleware$middleware$1$1$1.invoke(SelectorMiddleware.kt:18)
       at com.innopro.b4work.data.middleware.ConfirmPrivacyPolicyMiddleware$middleware$1$1$1.invoke(ConfirmPrivacyPolicyMiddleware.kt:18)
       at com.innopro.b4work.data.middleware.ConfirmPrivacyPolicyMiddleware$middleware$1$1$1.invoke(ConfirmPrivacyPolicyMiddleware.kt:14)
       at com.innopro.b4work.data.rgpd.RgpdMiddleware$middleware$1$1$1.invoke(RgpdMiddleware.kt:19)
       at com.innopro.b4work.data.rgpd.RgpdMiddleware$middleware$1$1$1.invoke(RgpdMiddleware.kt:15)
       at com.innopro.b4work.data.profile.appearance.AppearanceMiddleware$middleware$1$1$1.invoke(AppearanceMiddleware.kt:21)
       at com.innopro.b4work.data.profile.appearance.AppearanceMiddleware$middleware$1$1$1.invoke(AppearanceMiddleware.kt:15)
       at com.innopro.b4work.data.profile.photo.PhotoMiddleware$middleware$1$1$1.invoke(PhotoMiddleware.kt:24)
       at com.innopro.b4work.data.profile.photo.PhotoMiddleware$middleware$1$1$1.invoke(PhotoMiddleware.kt:19)
       at com.innopro.b4work.data.middleware.CvMiddleware$middleware$1$1$1.invoke(CvMiddleware.kt:34)
       at com.innopro.b4work.data.middleware.CvMiddleware$middleware$1$1$1.invoke(CvMiddleware.kt:27)
       at com.innopro.b4work.data.middleware.DeepLinkMiddleware$middleware$1$1$1.invoke(DeepLinkMiddleware.kt:24)
       at com.innopro.b4work.data.middleware.DeepLinkMiddleware$middleware$1$1$1.invoke(DeepLinkMiddleware.kt:19)
       at com.innopro.b4work.data.middleware.AnalyticsMiddleware$middleware$1$1$1.invoke(AnalyticsMiddleware.kt:38)
       at com.innopro.b4work.data.middleware.AnalyticsMiddleware$middleware$1$1$1.invoke(AnalyticsMiddleware.kt:19)
       at com.innopro.b4work.data.middleware.ProfileMiddleware$middleware$1$1$1.invoke(ProfileMiddleware.kt:50)
       at com.innopro.b4work.data.middleware.ProfileMiddleware$middleware$1$1$1.invoke(ProfileMiddleware.kt:28)
       at com.innopro.b4work.data.middleware.OfferMiddleware$middleware$1$1$1.invoke(OfferMiddleware.kt:173)
       at com.innopro.b4work.data.middleware.OfferMiddleware$middleware$1$1$1.invoke(OfferMiddleware.kt:50)
       at com.innopro.b4work.data.middleware.CompanyMiddleware$middleware$1$1$1.invoke(CompanyMiddleware.kt:90)
       at com.innopro.b4work.data.middleware.CompanyMiddleware$middleware$1$1$1.invoke(CompanyMiddleware.kt:34)
       at com.innopro.b4work.data.middleware.AccountMiddleware$middleware$1$1$1.invoke(AccountMiddleware.kt:65)
       at com.innopro.b4work.data.middleware.AccountMiddleware$middleware$1$1$1.invoke(AccountMiddleware.kt:25)
       at com.innopro.b4work.data.middleware.AppMiddleware$middleware$1$1$1.invoke(AppMiddleware.kt:40)
       at com.innopro.b4work.data.middleware.AppMiddleware$middleware$1$1$1.invoke(AppMiddleware.kt:22)
       at com.innopro.b4work.data.middleware.DbMiddleware$middleware$1$1$1.invoke(DbMiddleware.kt:96)
       at com.innopro.b4work.data.middleware.DbMiddleware$middleware$1$1$1.invoke(DbMiddleware.kt:19)
       at com.innopro.b4work.data.middleware.InscriptionMiddleware$middleware$1$1$1.invoke(InscriptionMiddleware.kt:186)
       at com.innopro.b4work.data.middleware.InscriptionMiddleware$middleware$1$1$1.invoke(InscriptionMiddleware.kt:28)
       at com.innopro.b4work.data.middleware.LoggingMiddleware$middleware$1$1$1.invoke(LoggingMiddleware.kt:13)
       at com.innopro.b4work.data.middleware.LoggingMiddleware$middleware$1$1$1.invoke(LoggingMiddleware.kt:11)
       at org.rekotlin.Store.dispatch(Store.kt:141)
       at com.innopro.b4work.newcode.presentation.base.RPresenter.dispatch(RPresenter.kt:57)
       at com.innopro.b4work.newcode.presentation.appHome.HomeActivityPresenter.newState(HomeActivityPresenter.kt:87)
       at com.innopro.b4work.newcode.presentation.appHome.HomeActivityPresenter.newState(HomeActivityPresenter.kt:41)
       at org.rekotlin.SubscriptionBox$$special$$inlined$let$lambda$1.invoke(Subscription.kt:69)
       at org.rekotlin.SubscriptionBox$$special$$inlined$let$lambda$1.invoke(Subscription.kt:35)
       at org.rekotlin.Subscription.newValues(Subscription.kt:178)
       at org.rekotlin.Subscription$1.invoke(Subscription.kt:170)
       at org.rekotlin.Subscription$1.invoke(Subscription.kt:83)
       at org.rekotlin.Subscription$skipRepeats$1$1.invoke(Subscription.kt:115)
       at org.rekotlin.Subscription$skipRepeats$1$1.invoke(Subscription.kt:83)
       at org.rekotlin.Subscription.newValues(Subscription.kt:178)
       at org.rekotlin.Subscription$1.invoke(Subscription.kt:170)
       at org.rekotlin.Subscription$1.invoke(Subscription.kt:83)
       at org.rekotlin.Subscription$_select$1$1.invoke(Subscription.kt:89)
       at org.rekotlin.Subscription$_select$1$1.invoke(Subscription.kt:83)
       at org.rekotlin.Subscription.newValues(Subscription.kt:178)
       at org.rekotlin.SubscriptionBox.newValues(Subscription.kt:79)
       at org.rekotlin.Store.set_state(Store.kt:42)
       at org.rekotlin.Store._defaultDispatch(Store.kt:137)
       at org.rekotlin.Store$dispatchFunction$1.invoke(Store.kt:53)
       at org.rekotlin.Store$dispatchFunction$1.invoke(Store.kt:29)
       at com.innopro.b4work.data.middleware.NpsMiddleware$middleware$1$1$1.invoke(NpsMiddleware.kt:46)
       at com.innopro.b4work.data.middleware.NpsMiddleware$middleware$1$1$1.invoke(NpsMiddleware.kt:24)
       at com.innopro.b4work.data.middleware.AlertsMiddleware$middleware$1$1$1.invoke(AlertsMiddleware.kt:33)
       at com.innopro.b4work.data.middleware.AlertsMiddleware$middleware$1$1$1.invoke(AlertsMiddleware.kt:24)
       at com.innopro.b4work.data.middleware.CompanyStatusMiddleware$middleware$1$1$1.invoke(CompanyStatusMiddleware.kt:23)
       at com.innopro.b4work.data.middleware.CompanyStatusMiddleware$middleware$1$1$1.invoke(CompanyStatusMiddleware.kt:14)
       at com.innopro.b4work.data.middleware.ChatMiddleware$middleware$1$1$1.invoke(ChatMiddleware.kt:23)
       at com.innopro.b4work.data.middleware.ChatMiddleware$middleware$1$1$1.invoke(ChatMiddleware.kt:17)
       at com.innopro.b4work.data.middleware.NotificationMiddleware$middleware$1$1$1.invoke(NotificationMiddleware.kt:20)
       at com.innopro.b4work.data.middleware.NotificationMiddleware$middleware$1$1$1.invoke(NotificationMiddleware.kt:15)
       at com.innopro.b4work.data.middleware.SelectorMiddleware$middleware$1$1$1.invoke(SelectorMiddleware.kt:22)
       at com.innopro.b4work.data.middleware.SelectorMiddleware$middleware$1$1$1.invoke(SelectorMiddleware.kt:18)
       at com.innopro.b4work.data.middleware.ConfirmPrivacyPolicyMiddleware$middleware$1$1$1.invoke(ConfirmPrivacyPolicyMiddleware.kt:18)
       at com.innopro.b4work.data.middleware.ConfirmPrivacyPolicyMiddleware$middleware$1$1$1.invoke(ConfirmPrivacyPolicyMiddleware.kt:14)
       at com.innopro.b4work.data.rgpd.RgpdMiddleware$middleware$1$1$1.invoke(RgpdMiddleware.kt:19)
       at com.innopro.b4work.data.rgpd.RgpdMiddleware$middleware$1$1$1.invoke(RgpdMiddleware.kt:15)
       at com.innopro.b4work.data.profile.appearance.AppearanceMiddleware$middleware$1$1$1.invoke(AppearanceMiddleware.kt:21)
       at com.innopro.b4work.data.profile.appearance.AppearanceMiddleware$middleware$1$1$1.invoke(AppearanceMiddleware.kt:15)
       at com.innopro.b4work.data.profile.photo.PhotoMiddleware$middleware$1$1$1.invoke(PhotoMiddleware.kt:24)
       at com.innopro.b4work.data.profile.photo.PhotoMiddleware$middleware$1$1$1.invoke(PhotoMiddleware.kt:19)
       at com.innopro.b4work.data.middleware.CvMiddleware$middleware$1$1$1.invoke(CvMiddleware.kt:34)
       at com.innopro.b4work.data.middleware.CvMiddleware$middleware$1$1$1.invoke(CvMiddleware.kt:27)
       at com.innopro.b4work.data.middleware.DeepLinkMiddleware$middleware$1$1$1.invoke(DeepLinkMiddleware.kt:24)
       at com.innopro.b4work.data.middleware.DeepLinkMiddleware$middleware$1$1$1.invoke(DeepLinkMiddleware.kt:19)
       at com.innopro.b4work.data.middleware.AnalyticsMiddleware$middleware$1$1$1.invoke(AnalyticsMiddleware.kt:38)
       at com.innopro.b4work.data.middleware.AnalyticsMiddleware$middleware$1$1$1.invoke(AnalyticsMiddleware.kt:19)
       at com.innopro.b4work.data.middleware.ProfileMiddleware$middleware$1$1$1.invoke(ProfileMiddleware.kt:50)
       at com.innopro.b4work.data.middleware.ProfileMiddleware$middleware$1$1$1.invoke(ProfileMiddleware.kt:28)
       at com.innopro.b4work.data.middleware.OfferMiddleware$middleware$1$1$1.invoke(OfferMiddleware.kt:173)
       at com.innopro.b4work.data.middleware.OfferMiddleware$middleware$1$1$1.invoke(OfferMiddleware.kt:50)
       at com.innopro.b4work.data.middleware.CompanyMiddleware$middleware$1$1$1.invoke(CompanyMiddleware.kt:90)
       at com.innopro.b4work.data.middleware.CompanyMiddleware$middleware$1$1$1.invoke(CompanyMiddleware.kt:34)
       at com.innopro.b4work.data.middleware.AccountMiddleware$middleware$1$1$1.invoke(AccountMiddleware.kt:65)
       at com.innopro.b4work.data.middleware.AccountMiddleware$middleware$1$1$1.invoke(AccountMiddleware.kt:25)
       at com.innopro.b4work.data.middleware.AppMiddleware$middleware$1$1$1.invoke(AppMiddleware.kt:40)
       at com.innopro.b4work.data.middleware.AppMiddleware$middleware$1$1$1.invoke(AppMiddleware.kt:22)
       at com.innopro.b4work.data.middleware.DbMiddleware$middleware$1$1$1.invoke(DbMiddleware.kt:96)
       at com.innopro.b4work.data.middleware.DbMiddleware$middleware$1$1$1.invoke(DbMiddleware.kt:19)
       at com.innopro.b4work.data.middleware.InscriptionMiddleware$middleware$1$1$1.invoke(InscriptionMiddleware.kt:186)
       at com.innopro.b4work.data.middleware.InscriptionMiddleware$middleware$1$1$1.invoke(InscriptionMiddleware.kt:28)
       at com.innopro.b4work.data.middleware.LoggingMiddleware$middleware$1$1$1.invoke(LoggingMiddleware.kt:13)
       at com.innopro.b4work.data.middleware.LoggingMiddleware$middleware$1$1$1.invoke(LoggingMiddleware.kt:11)
       at org.rekotlin.Store.dispatch(Store.kt:141)
       at org.rekotlin.Store$$special$$inlined$fold$lambda$1.invoke(Store.kt:54)
       at org.rekotlin.Store$$special$$inlined$fold$lambda$1.invoke(Store.kt:29)
       at com.innopro.b4work.data.middleware.CompanyStatusMiddleware$requestCompanyStatus$2.invoke(CompanyStatusMiddleware.kt:33)
       at com.innopro.b4work.data.middleware.CompanyStatusMiddleware$requestCompanyStatus$2.invoke(CompanyStatusMiddleware.kt:30)
       at com.innopro.b4work.data.middleware.BaseMiddleware$subscribeBy$1.invoke(BaseMiddleware.kt:36)
       at com.innopro.b4work.data.middleware.BaseMiddleware$subscribeBy$1.invoke(BaseMiddleware.kt:35)
       at com.innopro.b4work.data.middleware.BaseMiddleware.subscribeBy$lambda$0(BaseMiddleware.kt:35)
       at com.innopro.b4work.data.middleware.BaseMiddleware.$r8$lambda$KRO7OmuMtoGM-LVMHlSkJN0Sfe0()
       at com.innopro.b4work.data.middleware.BaseMiddleware$$ExternalSyntheticLambda2.accept(:2)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:224)
       at android.os.Looper.loop(Looper.java:318)
       at android.app.ActivityThread.main(ActivityThread.java:8775)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by albertB4work** [comment]
> org.rekotlin.Store._defaultDispatch Store.kt:125 org.rekotlin.Store$dispatchFunction$1.invoke Store.kt:53 org.rekotlin.Store$dispatchFunction$1.invoke Store.kt:29 com.outsidesource.oskit.domain.store.middleware.effectReducer.MiddlewareKt$createEffectReducerMiddleware$1$1$1.invoke Middleware.kt:48 com.outsidesource.oskit.domain.store.middleware.effectReducer.MiddlewareKt$createEffectReducerMiddleware$1$1$1.invoke com.outsidesource.oskit.domain.store.middleware.ActionCoordinator$createMiddleware$1$1$1.invoke ActionCoordinator.kt:79 com.outsidesource.oskit.domain.store.middleware.ActionCoordinator$createMiddleware$1$1$1.invoke ActionCoordinator.kt:59 org.rekotlin.Store.dispatch Store.kt:141 org.rekotlin.Store$$special$$inlined$fold$lambda$1.invoke Store.kt:54 org.rekotlin.Store$$special$$inlined$fold$lambda$1.invoke Store.kt:29 com.outsidesource.oskit.domain.store.middleware.effectReducer.MiddlewareKt$handleDispatchEffect$2.invokeSuspend Middleware.kt:239 kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith ContinuationImpl.kt:33 kotlinx.coroutines.DispatchedTask.run DispatchedTask.kt:106 android.os.Handler.handleCallback Handler.java:942 android.os.Handler.dispatchMessage Handler.java:99 android.os.Looper.loopOnce Looper.java:226 android.os.Looper.loop Looper.java:313 android.app.ActivityThread.main ActivityThread.java:8762 java.lang.reflect.Method.invoke Method.java com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:604 com.android.internal.os.ZygoteInit.main ZygoteInit.java:1067

I think I will clone the library some day and try to update it with a fix for this
